const GOOGLE_DRIVE_CLIENT_ID = `438338719524-k0bmchdtihvlbh5bnh2rmpls1m51pk4f.apps.googleusercontent.com`
const GOOGLE_DRIVE_CLIENT_SECRET = `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`
const GOOGLE_DRIVE_REDIRECT_URI = `https://developers.google.com/oauthplayground`
const GOOGLE_DRIVE_REFRESH_TOKEN = `1//04XRea9CkCWj6CgYIARAAGAQSNwF-L9IrNQyOkTW9f_q1h2rc9B15zVwsT1UHwPMvxHNwHdH_93FT_D33vG0ZZVFiNWfcoajYsw8`
const GOOGLE_DRIVE_FOLDER_ID = `1Joq74uis77FzXb8kjjXbxP9gTcrGvZQM`

module.exports = {
    GOOGLE_DRIVE_CLIENT_ID,
    GOOGLE_DRIVE_CLIENT_SECRET,
    GOOGLE_DRIVE_REDIRECT_URI,
    GOOGLE_DRIVE_REFRESH_TOKEN,
    GOOGLE_DRIVE_FOLDER_ID
}